// <auto-generated />
namespace Biblioteca.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Reactualizare : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Reactualizare));
        
        string IMigrationMetadata.Id
        {
            get { return "202408230757054_Reactualizare"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
